import type { Airport, Airline } from '@/types/flight';

export const mockAirports: Airport[] = [
  { code: 'ISB', city: 'Islamabad', name: 'Islamabad International Airport', country: 'Pakistan' },
  { code: 'LHE', city: 'Lahore', name: 'Allama Iqbal International Airport', country: 'Pakistan' },
  { code: 'KHI', city: 'Karachi', name: 'Jinnah International Airport', country: 'Pakistan' },
  { code: 'PEW', city: 'Peshawar', name: 'Bacha Khan International Airport', country: 'Pakistan' },
  { code: 'UET', city: 'Quetta', name: 'Quetta International Airport', country: 'Pakistan' },
  { code: 'SKT', city: 'Sialkot', name: 'Sialkot International Airport', country: 'Pakistan' },
  { code: 'MUX', city: 'Multan', name: 'Multan International Airport', country: 'Pakistan' },
  { code: 'DMM', city: 'King Fahd International Airport', name: 'King Fahd International Airport', country: 'Saudi Arabia' },
  { code: 'JED', city: 'Jeddah', name: 'King Abdulaziz International Airport', country: 'Saudi Arabia' },
  { code: 'MED', city: 'Madinah', name: 'Prince Mohammad bin Abdulaziz International Airport', country: 'Saudi Arabia' },
  { code: 'DXB', city: 'Dubai', name: 'Dubai International Airport', country: 'United Arab Emirates' },
  { code: 'DOH', city: 'Doha', name: 'Hamad International Airport', country: 'Qatar' },
  { code: 'IST', city: 'Istanbul', name: 'Istanbul Airport', country: 'Türkiye' },
  { code: 'LHR', city: 'London', name: 'Heathrow Airport', country: 'United Kingdom' },
  { code: 'JFK', city: 'New York', name: 'John F. Kennedy International', country: 'United States' },
  { code: 'CDG', city: 'Paris', name: 'Charles de Gaulle', country: 'France' },
  { code: 'IST', city: 'Istanbul', name: 'Istanbul Airport', country: 'Türkiye' },
  { code: 'SIN', city: 'Singapore', name: 'Changi Airport', country: 'Singapore' },
  { code: 'HND', city: 'Tokyo', name: 'Haneda Airport', country: 'Japan' },
  { code: 'SYD', city: 'Sydney', name: 'Sydney Kingsford Smith', country: 'Australia' },
  { code: 'FRA', city: 'Frankfurt', name: 'Frankfurt am Main', country: 'Germany' },
  { code: 'AMS', city: 'Amsterdam', name: 'Amsterdam Schiphol', country: 'Netherlands' },
  { code: 'BOM', city: 'Mumbai', name: 'Chhatrapati Shivaji Maharaj International', country: 'India' },
  { code: 'YYZ', city: 'Toronto', name: 'Toronto Pearson', country: 'Canada' },
  { code: 'GRU', city: 'Sao Paulo', name: 'Sao Paulo Guarulhos', country: 'Brazil' },
  { code: 'CPT', city: 'Cape Town', name: 'Cape Town International', country: 'South Africa' },
  { code: 'HKG', city: 'Hong Kong', name: 'Hong Kong International', country: 'Hong Kong' },
  { code: 'BCN', city: 'Barcelona', name: 'Barcelona-El Prat', country: 'Spain' },
  { code: 'FCO', city: 'Rome', name: 'Fiumicino', country: 'Italy' },
  { code: 'BKK', city: 'Bangkok', name: 'Suvarnabhumi', country: 'Thailand' },
];

export const mockAirlines: Airline[] = [
  { code: 'PK', name: 'Pakistan International Airlines' },
  { code: 'PA', name: 'Airblue' },
  { code: 'ER', name: 'SereneAir' },
  { code: 'PF', name: 'AirSial' },
  { code: 'FZ', name: 'flydubai' },
  { code: 'EK', name: 'Emirates' },
  { code: 'QR', name: 'Qatar Airways' },
  { code: 'SV', name: 'Saudia' },
  { code: 'G9', name: 'Air Arabia' },
  { code: 'TK', name: 'Turkish Airlines' },
  { code: 'BA', name: 'British Airways' },
  { code: 'AF', name: 'Air France' },
  { code: 'SQ', name: 'Singapore Airlines' },
  { code: 'JL', name: 'Japan Airlines' },
  { code: 'QF', name: 'Qantas Airways' },
  { code: 'LH', name: 'Lufthansa' },
  { code: 'KL', name: 'KLM Royal Dutch Airlines' },
  { code: 'AI', name: 'Air India' },
  { code: 'AC', name: 'Air Canada' },
  { code: 'AA', name: 'American Airlines' },
  { code: 'DL', name: 'Delta Air Lines' },
  { code: 'UA', name: 'United Airlines' },
  { code: 'CX', name: 'Cathay Pacific' },
];
